<?php
get_header();
?>
<main>
<section class="bay bay--flush" style="padding-top:clamp(4rem,9vw,7rem)"><div class="shell"><div class="hero__meta o" style="margin-bottom:var(--s-5)"><span class="datum" aria-hidden="true"><i></i><i></i><i></i></span><span class="note">Sheet 01 of 05</span><span class="note note--red">The crew</span></div><h1 class="o" style="font-size:var(--t-xxl);max-width:16ch">Twenty-five students.<br>One shop. <em style="font-style:normal;color:var(--red)">One deadline.</em></h1><p class="o" style="max-width:56ch;margin-top:var(--s-5);font-size:var(--t-md);color:var(--chalk-2)">There is no tryout and no prerequisite. Show up at the shop, pick a subteam, and by February you will have built something that moves.</p></div></section>

<section class="bay bay--flush" style="padding-top:0"><div class="shell"><figure class="crew" data-reveal><?php echo wp_kses_post( technotics_image_or_placeholder( 'tech_team_image', '', 'FRC Team 1635 roster photo' ) ); ?><figcaption class="crew__plate"><strong>The current crew</strong><span class="note">NEW TOWN HS · 2026 SEASON · STUDENTS &amp; MENTORS</span></figcaption></figure></div></section>

<section class="bay"><div class="shell"><div class="titleblock" data-reveal><span class="note note--red titleblock__tag">§ 01 — Why we do it</span><h2>The robot is the excuse. The engineers are the point.</h2></div><div class="split"><div class="prose" data-reveal><p class="lede">Newtown High School sits in Elmhurst, one of the most linguistically diverse neighbourhoods on earth. Our roster reflects it exactly.</p><p>Each January FIRST releases the season's game. Six weeks later a 120-pound robot has to pass inspection. In between, students learn mechanical design, electrical systems, software and project management with something real on the line and a clock running.</p><p>Most students arrive knowing nothing. That is the intended starting point. The seniors running our mill were freshmen who could not read a caliper three years ago.</p></div><figure class="frame frame--fit" style="aspect-ratio:4/3" data-reveal data-fx="scale"><?php echo wp_kses_post( technotics_image_or_placeholder( 'tech_about_image', '', 'Students working in the shop' ) ); ?></figure></div></div></section>

<section class="bay bay--steel"><div class="shell"><div class="titleblock" data-reveal><span class="note note--red titleblock__tag">§ 02 — Structure</span><h2>Five subteams. One robot.</h2><p>Pick one in October. Nobody stays boxed in — half the team ends up cross-trained by January anyway.</p></div><div class="units" data-wave><article class="unit"><span class="note note--red">01</span><h3>Mechanical</h3><p>Drivetrains, intakes, manipulators. The students with aluminium chips in their hoodies.</p><ul class="chips"><li>Mill</li><li>Lathe</li><li>3D print</li><li>Sheet metal</li></ul></article><article class="unit"><span class="note note--red">02</span><h3>Electrical</h3><p>Battery to motor controller to RoboRIO and back. If it has a wire on it, it ends up here.</p><ul class="chips"><li>CAN bus</li><li>PDH</li><li>Harness</li><li>Sensors</li></ul></article><article class="unit"><span class="note note--red">03</span><h3>Programming</h3><p>Autonomous routines, drive-team telemetry, and vision when the game calls for it.</p><ul class="chips"><li>Java</li><li>WPILib</li><li>Auto</li><li>Vision</li></ul></article><article class="unit"><span class="note note--red">04</span><h3>Design / CAD</h3><p>Concept sketch to fully-toleranced assembly. The bridge between strategy and the machine shop.</p><ul class="chips"><li>Fusion</li><li>Onshape</li><li>DFM</li></ul></article><article class="unit"><span class="note note--red">05</span><h3>Business &amp; Outreach</h3><p>Sponsors, fundraising, the team binder, and demos we bring into schools across Queens.</p><ul class="chips"><li>Sponsors</li><li>Comms</li><li>Outreach</li></ul></article><article class="unit" style="background:var(--graphite)"><span class="note" style="color:var(--amber)">06</span><h3>Mentors</h3><p>Faculty, working engineers and alumni who show up after the bell to teach milling and design review.</p><ul class="chips"><li>NHS faculty</li><li>Engineers</li><li>Alumni</li></ul></article></div></div></section>

<section class="bay"><div class="shell"><div class="titleblock" data-reveal><span class="note note--red titleblock__tag">§ 03 — Build season</span><h2>Kickoff crate to competition floor in about 45 days.</h2><p>The same six weeks every team on earth gets.</p></div><div class="rail" data-nudge data-reveal><article class="week"><span class="week__no">01</span><span class="note note--red">Jan · Kickoff</span><h3>Read the rules. Argue strategy.</h3><p>Whole team in one room with whiteboards, the kit-of-parts and pizza.</p></article><article class="week"><span class="week__no">02</span><span class="note note--red">Prototype</span><h3>Wood, zip-ties, bad ideas.</h3><p>Mechanisms in plywood and extrusion. The survivors become real subsystems.</p></article><article class="week"><span class="week__no">03</span><span class="note note--red">CAD lock</span><h3>Design the whole machine.</h3><p>Prototypes become a full assembly before a chip is cut.</p></article><article class="week"><span class="week__no">04</span><span class="note note--red">Manufacture</span><h3>CNC, mill, print, repeat.</h3><p>Parts come off the mill and the printers.</p></article><article class="week"><span class="week__no">05</span><span class="note note--red">Integrate</span><h3>Wire it. Code it. Break it.</h3><p>Subsystems mounted, electronics flashed, autonomous run over and over.</p></article><article class="week"><span class="week__no">06</span><span class="note note--red">Compete</span><h3>Load the truck.</h3><p>Final tuning, driver practice, binder finished — then an early bus to the Armory.</p></article></div></div></section>

<section class="band"><div class="band__inner"><span class="note">[ Open door ]</span>You do not need to know anything. You need to show up.</div></section>
<section class="bay bay--flush"><div class="shell" style="text-align:center"><a href="<?php echo esc_url( technotics_page_url( 'contact' ) ); ?>" class="btn" data-magnetic data-reveal>Ask about joining <svg width="14" height="14" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" stroke-width="1.6"/></svg></a></div></section>
</main>
<?php get_footer(); ?>
