<?php
get_header();
?>
<main>
<section class="bay bay--flush" style="padding-top:clamp(4rem,9vw,7rem)"><div class="shell"><div class="hero__meta o" style="margin-bottom:var(--s-5)"><span class="datum" aria-hidden="true"><i></i><i></i><i></i></span><span class="note">Sheet 02 of 05</span><span class="note note--red">The machine</span></div><h1 class="o" style="font-size:var(--t-xxl);max-width:16ch">AJ.<br><em style="font-style:normal;color:var(--red)">Built to move.</em></h1><p class="o" style="max-width:56ch;margin-top:var(--s-5);font-size:var(--t-md);color:var(--chalk-2)">Custom six-wheel base. Compliant-roller intake. Two-stage elevator, articulated arm and flywheel launcher.</p></div></section>

<section class="bay bay--flush" style="padding-top:0"><div class="shell"><figure class="frame" style="aspect-ratio:16/8" data-reveal data-fx="clip"><?php echo wp_kses_post( technotics_image_or_placeholder( 'tech_robot_image', '', 'AJ, the 2026 competition robot' ) ); ?><figcaption class="note">FIG.00 — AJ · 2026 COMPETITION ROBOT</figcaption></figure></div></section>

<section class="bay"><div class="shell"><div class="titleblock" data-reveal><span class="note note--red titleblock__tag">§ 01 — By the numbers</span><h2>Every part has a job.</h2><p>A compact machine built around reliable motion, repeatable scoring and a driver-friendly interface.</p></div><div class="specs" data-wave><div class="spec"><span class="note note--red">Drive</span><b>Tank · 6WD</b><small>Belt-in-tube, centre drop</small></div><div class="spec"><span class="note note--red">Motors</span><b>NEO brushless</b><small>Paired per side</small></div><div class="spec"><span class="note note--red">Frame</span><b>Sheet aluminium</b><small>In-house CNC &amp; mill</small></div><div class="spec"><span class="note note--red">Intake</span><b>Roller stack</b><small>Compliant wheels</small></div><div class="spec"><span class="note note--red">Elevator</span><b>Two-stage</b><small>Cascading, belt driven</small></div><div class="spec"><span class="note note--red">Launcher</span><b>Twin flywheel</b><small>Tuned hood, variable RPM</small></div><div class="spec"><span class="note note--red">Code</span><b>Java · WPILib</b><small>Auto routines + vision</small></div><div class="spec"><span class="note note--red">Bumpers</span><b>16 / 35</b><small>Red, regulation FRC</small></div></div></div></section>

<section class="stage" id="assembly"><div class="stage__pin"><canvas id="exploded" aria-hidden="true"></canvas><div class="stage__hud"><div class="stage__readout is-in" data-stage-step><span class="note note--red">Stage 01 · Assembled</span><h2>Ready for inspection.</h2><p>Competition configuration. Bumpers on, battery in, inspected and cleared for the field.</p></div><div class="stage__readout" data-stage-step><span class="note note--red">Stage 02 · Superstructure</span><h2>Motion, separated.</h2><p>Launcher, elevator and intake pull away so the architecture can be read.</p></div><div class="stage__readout" data-stage-step><span class="note note--red">Stage 03 · Powertrain</span><h2>Six wheels. One chain.</h2><p>Power flows from the battery through the bus and into a drivetrain tuned for control.</p></div><div class="stage__readout" data-stage-step><span class="note note--red">Stage 04 · Fully exploded</span><h2>Nothing hidden.</h2><p>Every assembly was designed, fabricated, wired and tested by students.</p></div></div><div class="stage__scrub" aria-hidden="true"><i class="is-on"></i><i></i><i></i><i></i></div></div></section>

<section class="bay"><div class="shell"><div class="titleblock" data-reveal><span class="note note--red titleblock__tag">§ 02 — Subsystems</span><h2>Three mechanisms. A hundred small decisions.</h2></div><div class="mechs">
<?php $mechanisms = array( 'drivetrain' => array( 'Drivetrain', 'Six-wheel base, centre drop and a driver-first control feel.', 'assets/images/drivetrain-1.png', 'assets/images/drivetrain-2.png', 'assets/images/drivetrain-3.png' ), 'intake' => array( 'Intake', 'Compliant rollers pull game pieces into a guided path without asking the driver for perfection.', 'assets/images/intake-1.png', 'assets/images/intake-2.png', 'assets/images/intake-3.png' ), 'launcher' => array( 'Launcher', 'A twin-wheel flywheel and tuned hood turn repeatable RPM into repeatable scoring.', 'assets/images/launcher-1.png', 'assets/images/launcher-2.png', 'assets/images/launcher-3.png' ) ); $n = 0; foreach ( $mechanisms as $mechanism ) : ?>
<figure class="mech" data-reveal data-fx="scale" style="--i:<?php echo esc_attr( $n++ ); ?>"><div class="mech__view"><div class="reel"><img src="<?php echo esc_url( technotics_asset_url( $mechanism[2] ) ); ?>" alt="<?php echo esc_attr( $mechanism[0] ); ?>" class="is-on"><img src="<?php echo esc_url( technotics_asset_url( $mechanism[3] ) ); ?>" alt=""><img src="<?php echo esc_url( technotics_asset_url( $mechanism[4] ) ); ?>" alt=""></div></div><figcaption class="mech__body"><span class="note note--red">0<?php echo esc_html( $n ); ?> · <?php echo esc_html( strtoupper( $mechanism[0] ) ); ?></span><h3><?php echo esc_html( $mechanism[0] ); ?></h3><p><?php echo esc_html( $mechanism[1] ); ?></p></figcaption></figure>
<?php endforeach; ?></div></div></section>

<section class="bay bay--steel"><div class="shell"><div class="split"><div class="prose" data-reveal><span class="note note--red titleblock__tag">§ 03 — In the pit</span><h2>Load in Friday morning. Keep a laptop and a soldering iron close.</h2><p class="lede">The robot is never really finished. It is only ready for the next match.</p><p>Every subsystem has a student owner, a checklist and a failure mode we have already seen once.</p></div><figure class="frame" style="aspect-ratio:4/3" data-reveal data-fx="scale"><div class="tech-placeholder"><span class="note">ADD A PIT PHOTO IN APPEARANCE → CUSTOMIZE</span></div><figcaption class="note">PIT CREW · NYC REGIONAL</figcaption></figure></div></div></section>
</main>
<?php get_footer(); ?>
